### ISSUE TITLE
Fails to execute

### ISSUE THREAD

**Issue by ghost** [jefferyto/faux-gnome-screensaver#4]
When executing faux-gnome-screensaver or gnome-screensaver I get the following:
`Traceback (most recent call last):
  File "/usr/local/bin/gnome-screensaver", line 836, in <module>
    sys.exit(main(argv))
  File "/usr/local/bin/gnome-screensaver", line 804, in main
    getobj(k).activate()
  File "/usr/local/bin/gnome-screensaver", line 653, in activate
    for key, info in self.SETTINGS.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems`

I'm using Arch with python 3.10.4.

**Comment by jefferyto** [comment]
If you really want to try making this work, you can change the three instances of `iteritems` (for Python 2) in that file to `items` (for Python 3), but even then I highly doubt it will work correctly.

I haven't used or updated these scripts in years, and I don't recommend you try. In fact, I'm going to archive this repo (thanks for reminding me).
